INSERT [dbo].[Localization_Culture] ([Id], [Name]) VALUES ('pl-PL', N'Polski')
GO

INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Register', N'Rejestracja')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Hello {0}!', N'Witaj, {0}!')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Log in', N'Zaloguj')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Log off', N'Wyloguj')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'The Email field is required.', N'Pole Email jest wymagane')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Email', N'Email')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'User List', N'Lista użytkowników')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Remember me?', N'Zapamiętaj mnie')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Password', N'Hasło')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Use a local account to log in.', N'Użyj konta lokalnego, aby się zalogować.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Register as a new user?', N'Zarejestruj się jako nowy użytkownik?')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Forgot your password?', N'Zapomniałeś hasła?')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Use another service to log in.', N'Użyj konta w innym serwisie.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Full name', N'Imię i nazwisko')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Confirm password', N'Powtórz hasło')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Create a new account.', N'Utwórz nowe konto.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'All', N'Wszystko')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Home', N'Strona startowa')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Add to cart', N'Dodaj do koszyka')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Product detail', N'Szczegóły')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Product specification', N'Specyfikacja produktu')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Rate this product', N'Oceń ten produkt')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Review comment', N'Podgląd tekstu')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Review title', N'Podgląd tytułu')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Posted by', N'Autor')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Submit review', N'Dodaj recenzję')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'You have', N'Masz')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'products in your cart', N'produktów w koszyku.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Continue shopping', N'Kontunuuj zakupy')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'View cart', N'Przejdź do koszyka')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'The product has been added to your cart', N'Produkt został dodany do koszyka')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Cart subtotal', N'Suma częściowa')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Shopping Cart', N'Koszyk')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Product', N'Produkt')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Price', N'Cena')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Quantity', N'Ilość')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'There are no items in this cart.', N'Brak produktów w tym koszyku.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Go to shopping', N'Przejdź do zakupów')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Order summary', N'Podsumowanie zamowienia')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Subtotal', N'Razem')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Process to Checkout', N'Złóż zamówienie')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Shipping address', N'Adres wysyłki')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Add another address', N'Dodaj kolejny adres')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Contact name', N'Imię i nazwisko osoby kontaktowej')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Address', N'Adres')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'State or Province', N'Województwo')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'District', N'Powiat')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Phone', N'Telefon')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Order', N'Zamów')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'products', N'produkty')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'reviews', N'recenzje')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Add Review', N'Dodaj recenzję')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Customer reviews', N'Recenzje klientów')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Your review will be showed within the next 24h.', N'Twoja opinia zostanie opublikowana w ciągu 24 godzin.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Thank you {0} for your review', N'Dziękujemy {0} za Twoją opinię.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Rating average', N'Średnia ocena')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'stars', N'gwiazdek')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Filter by', N'Filtruj po')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Category', N'Kategoria')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Brand', N'Marka')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Sort by:', N'Sortuj po:')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'results', N'wynik')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Add to Compare', N'Dodaj do porównania')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Not available', N'Nie dostępny')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'You save', N'Zapisałeś')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Submit', N'Wyślij')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'All Categories', N'Wszystkie kategorie')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('pl-PL', N'Search here...', N'Szukaj')
GO
